pool:
  vmImage: Ubunutu 16.04

steps:
  - script: make linux
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/dist'
      artifactName: 'building-v($Build.BuildNumber)'
